services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT Check_30kaUser_bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true