services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Check_30kaUser_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
    autoDeploy: true